---
- hosts: all
  become: yes
  tasks:
    - name: Kill any running instance first.
      shell: killall java

    - name: start cantaloupe
      shell: "(sudo -u cantaloupe nohup java -Dcantaloupe.config=/opt/cantaloupe/cantaloupe.properties -Xmx7g -jar Cantaloupe-{{ cantaloupe_version }}.war >/dev/null 2>&1 &)"
      args:
        chdir: /opt/cantaloupe
